<template>
<div class="asset-page">
<div class="page-heading asset-heading"><RouterLink :to="backLink">← {{ backLabel }}</RouterLink><div class="panel-head"><h2>{{ asset.name || asset.symbol || short(address) }} <small>{{ asset.name?asset.symbol:'' }}</small></h2><button :aria-pressed="followed" @click="account.toggle(watchKey)">{{ followed?tr('★ 已关注','★ Following'):tr('☆ 关注','☆ Follow') }}</button><a v-if="dex" class="asset-dex-action" :href="dex.url" target="_blank" rel="noopener" :title="tr('打开外部行情与交易页面','Open external market and swap page')">{{ tr('去 DEX','Open DEX') }} · {{ dex.provider }} ↗</a></div><p>{{ chainName({chainId:chain}) }} · <span :title="address">{{ short(address) }}</span> <button class="text-button" @click="copyAddress">{{ copied?tr('已复制','Copied'):tr('复制地址','Copy') }}</button> · <a :href="explorer(address,'address',chain)" target="_blank" rel="noopener">{{ tr('链上记录','Onchain') }} ↗</a></p></div>
<section v-if="error&&!data" class="panel x-empty" role="alert">{{ tr('资产暂时无法加载。','This asset could not be loaded.') }} <button @click="load(true)">{{ tr('重试','Retry') }}</button></section>
<section v-else-if="!data" class="panel loading-skeleton" role="status" :aria-label="tr('加载资产','Loading asset')"><div v-for="n in 5" :key="n" class="skeleton-line"></div></section>
<template v-else>
<p v-if="error" class="hint" role="status">{{ tr('更新暂时失败，保留上次行情。','Update failed; showing the previous quote.') }}</p>
<div class="asset-price-line" :title="metricTitle('price')"><LiveNumber :value="asset.price" :currency="asset.priceCurrency" format="price" /><b :class="Number(asset.change24h)>0?'up':Number(asset.change24h)<0?'down':''">{{ pct(asset.change24h) }} <small>24h</small></b><QuoteStatus :row="asset" /></div>
<div class="asset-kpis"><div :title="metricTitle('volume24h')"><span>{{ tr('24h 成交额','24h volume') }}</span><strong><LiveNumber :value="asset.volume24h" :currency="asset.volumeCurrency" /></strong></div><div :title="metricTitle('totalLiquidityUsd')"><span>{{ tr('总流动性','Liquidity') }}</span><strong><LiveNumber :value="asset.totalLiquidityUsd" /></strong></div><div :title="metricTitle('txs24h')"><span>{{ tr('24h 买入 / 卖出','24h buys / sells') }}</span><strong><span class="up">{{ num(asset.buys24h) }}</span> / <span class="down">{{ num(asset.sells24h) }}</span></strong></div><div :title="metricTitle('holders')"><span>{{ tr('持币地址','Holders') }}</span><strong><LiveNumber :value="asset.holders" format="number" /></strong></div></div>
<nav class="asset-tabs" :aria-label="tr('资产栏目','Asset sections')"><RouterLink v-for="tab in tabs" :key="tab.key" :to="{query:{...route.query,tab:tab.key}}" :class="{active:activeTab===tab.key}" :aria-current="activeTab===tab.key?'page':undefined">{{ tr(tab.zh,tab.en) }}</RouterLink></nav>
<template v-if="activeTab==='overview'">
<AssetInsight :chain="chain" :address="address" />
<section class="panel"><h2>{{ tr('风险检查','Risk checks') }}</h2><RiskSummary :asset="asset" /></section>
<div class="asset-overview-grid"><section class="panel asset-chart-panel"><div class="panel-head"><h2>{{ tr('价格走势','Price history') }}</h2><label>{{ tr('图表市场','Chart market') }} <select data-chart-market :value="marketSelection.id" @change="choice=$event.target.value"><option :value="asset.priceScope==='exchange'?'base':'dex'">{{ chartBaseLabel }}</option><option v-for="m in exchangeMarkets" :key="`${m.venue}:${m.marketId}`" :value="`${m.venue}:${m.marketId}`">{{ m.provider??m.venue }} · {{ m.marketId }} · {{ m.priceCurrency }}</option><option v-for="p in poolMarkets" :key="p.poolId??p.pool??p.marketId" :value="`pool:${p.poolId??p.pool??p.marketId}`">{{ short(p.poolId??p.pool??p.marketId) }} · {{ p.priceCurrency }}</option></select></label></div><p v-if="selectedPoolId" class="hint" data-pool-unit>{{ tr('所选池以','Selected pool currency:') }} {{ marketSelection.pool.priceCurrency || '—' }}{{ tr('计价','') }} · {{ tr('资产价格仍为主行情报价','Asset price uses the primary quote') }}</p><CandleChart :asset="chartAsset" :samples="data.samples??[]" :pool="selectedPoolId" :native-pool="nativePool" @select-pool="selectNativePool" /><p v-if="sectionErrors.markets" class="hint">{{ tr('市场列表暂时无法更新。','Market list is temporarily unavailable.') }} <button @click="loadSection('markets',true)">{{ tr('重试','Retry') }}</button></p></section><aside class="panel asset-live-trades"><div class="panel-head"><h2>{{ tr('最新成交','Latest trades') }}</h2><RouterLink :to="{query:{...route.query,tab:'trades'}}">{{ tr('全部','All') }} →</RouterLink></div><small class="hint">{{ tradeStatus }}</small><small class="hint" data-trade-scope>{{ tradeScopeLabel }}</small><div v-if="loading.trades&&!trades.length" class="loading-skeleton"><div v-for="n in 5" :key="n" class="skeleton-line"></div></div><div v-for="t in trades.slice(0,8)" :key="tradeKey(t)" class="asset-trade-mini"><time :title="date(t.t)">{{ age(t.t) }}</time><span :class="t.type==='buy'?'up':t.type==='sell'?'down':''">{{ t.type==='buy'?tr('买入','Buy'):t.type==='sell'?tr('卖出','Sell'):'—' }}</span><b :title="tradeSourceTitle(t)"><TradeAmount :trade="t" /></b></div><p v-if="sectionErrors.trades" class="hint" role="alert">{{ tr('成交暂时无法更新。','Trades could not be updated.') }} <button @click="loadSection('trades',true)">{{ tr('重试','Retry') }}</button></p><p v-else-if="!trades.length&&!loading.trades" class="x-empty">{{ tr('暂无已收录成交','No recorded trades') }}</p></aside></div>
<section class="panel asset-facts"><h2>{{ tr('资产概况','Asset snapshot') }}</h2><dl><div><dt>{{ tr('关联股票','Related stocks') }}</dt><dd><template v-if="tickers.length"><RouterLink v-for="ticker in tickers" :key="ticker" :to="`/stock/${encodeURIComponent(ticker)}`">{{ ticker }} </RouterLink></template><span v-else>—</span></dd></div><div><dt>{{ tr('关系类型','Relationship') }}</dt><dd>{{ relationshipLabel }}</dd></div><div><dt>{{ tr('行情来源','Quote source') }}</dt><dd>{{ asset.primaryQuote?.provider??asset.fieldSources?.price??asset.provider??'—' }} · {{ date(asset.fieldTimes?.price) }}</dd></div><div><dt>{{ tr('首次收录','First indexed') }}</dt><dd>{{ date(asset.firstSeen) }}</dd></div></dl></section>
<SpreadPanel v-if="asset.kind==='stock'" :chain="chain" :token="address" />
</template>
<section v-else-if="activeTab==='trades'" class="panel"><div class="panel-head"><h2>{{ tr('最新成交','Latest trades') }}</h2><span class="hint">{{ tradeStatus }}</span></div><p class="hint">{{ tr('已接入市场的成交记录；时间为实际成交时间。','Trades from connected markets, shown at their trade time.') }}</p><div v-if="loading.trades&&!trades.length" class="loading-skeleton" role="status"><div v-for="n in 6" :key="n" class="skeleton-line"></div></div><div v-else-if="trades.length" class="table-wrap" data-market-trades><table class="tbl"><thead><tr><th>{{ tr('时间','Time') }}</th><th>{{ tr('方向','Side') }}</th><th>{{ tr('价格','Price') }}</th><th>{{ tr('成交额','Amount') }}</th><th>{{ tr('市场','Market') }}</th><th>{{ tr('钱包 / 交易','Wallet / transaction') }}</th></tr></thead><tbody><tr v-for="t in trades" :key="tradeKey(t)" :class="{'trade-new':now-(t.browserReceivedAt??t.receivedAt??0)<2000}"><td :title="date(t.t)">{{ age(t.t) }}</td><td :class="t.type==='buy'?'up':t.type==='sell'?'down':''">{{ t.type==='buy'?tr('买入','Buy'):t.type==='sell'?tr('卖出','Sell'):'—' }}</td><td :title="tradeSourceTitle(t)">{{ money(t.price,t.priceCurrency) }}</td><td :title="tradeSourceTitle(t)"><TradeAmount :trade="t" /></td><td>{{ t.source??t.provider??t.venue??'—' }}<small>{{ short(t.poolId??t.pool??t.marketId) }}</small></td><td><a v-if="t.hash" :href="explorer(t.hash,'tx',chain)" target="_blank" rel="noopener">{{ short(t.wallet??t.hash) }} ↗</a><span v-else>{{ short(t.wallet) }}</span></td></tr></tbody></table></div><p v-else class="x-empty">{{ tr('暂无已收录成交。','No recorded trades yet.') }}</p><button v-if="data.sectionNext?.trades!=null" :disabled="loading.trades" @click="loadSection('trades',true,data.sectionNext.trades)">{{ tr('加载更多','Load more') }}</button><p v-if="sectionErrors.trades" role="alert">{{ tr('成交读取失败。','Trades could not be loaded.') }} <button @click="loadSection('trades',true)">{{ tr('重试','Retry') }}</button></p></section>
<section v-else-if="activeTab==='holders'" class="panel"><h2>{{ tr('持仓分布','Holder distribution') }}</h2><p v-if="loading.holders" role="status">{{ tr('加载中…','Loading…') }}</p><div class="asset-kpis"><div :title="metricTitle('holders')"><span>{{ tr('持币地址','Holders') }}</span><strong>{{ num(asset.holders) }}</strong></div><div :title="holderSourceTitle"><span>{{ tr('前十大持仓占比','Top 10 holdings') }}</span><strong>{{ data.holdersSummary?.distribution?.top10Percent!=null?Number(data.holdersSummary.distribution.top10Percent).toFixed(1)+'%':'—' }}</strong><small>{{ tr('原始持仓，可能包含池子和合约地址','Raw holdings; may include pools and contracts') }}</small></div></div><RiskSummary :asset="asset" /><p class="hint">{{ tr('调整后的集中度仅在地址排除信息完整时显示。','Adjusted concentration is available only with complete address exclusions.') }}</p><p v-if="sectionErrors.holders" role="alert">{{ tr('持仓读取失败。','Holdings could not be loaded.') }} <button @click="loadSection('holders',true)">{{ tr('重试','Retry') }}</button></p></section>
<section v-else class="panel"><div class="panel-head"><h2>{{ tr('股票关联','Stock relationships') }}</h2><span class="hint">{{ relations.length }} / {{ data.relationCount??relations.length }}</span></div><p v-if="loading.relations" role="status">{{ tr('加载中…','Loading…') }}</p><article v-for="r in relations" :key="r.id??`${r.chainId??chain}:${r.pool??r.token}:${r.ticker}`" class="asset-relation"><div class="panel-head"><RouterLink :to="`/stock/${encodeURIComponent(r.ticker)}`"><h3>{{ r.ticker }}</h3></RouterLink><RelationBadge :relation="r" /></div><div class="relation-flow"><RouterLink :to="{path:`/asset/${r.chainId??chain}/${r.token}`,query:{tab:'overview',pool:r.pool}}">{{ short(r.token) }}</RouterLink><span v-if="r.pool">↔</span><a v-if="r.pool" :href="explorer(r.pool,'address',String(r.chainId??chain))" target="_blank" rel="noopener">{{ r.protocol }} · {{ short(r.pool) }} ↗</a><template v-if="r.stock"><span>↔</span><a :href="explorer(r.stock,'address',String(r.chainId??chain))" target="_blank" rel="noopener">{{ short(r.stock) }} ↗</a></template></div><p v-if="r.pool" class="hint" :title="`${r.liquiditySource??r.provider??'—'} · ${date(r.liquidityAt)}`">{{ tr('池流动性','Pool liquidity') }} {{ usd(r.liquidityUsd) }} · {{ age(r.liquidityAt) }}</p><RegistryBadge v-if="r.pool" :relation="r" /></article><p v-if="!relations.length&&!loading.relations" class="x-empty">{{ tr('暂无股票关联。','No stock relationships yet.') }}</p><button v-if="data.sectionNext?.relations!=null" :disabled="loading.relations" @click="loadSection('relations',true,data.sectionNext.relations)">{{ tr('加载更多','Load more') }}</button><p v-if="sectionErrors.relations" role="alert">{{ tr('关联读取失败。','Relationships could not be loaded.') }} <button @click="loadSection('relations',true)">{{ tr('重试','Retry') }}</button></p></section>
</template></div>
</template>
<script setup>
import {computed,onBeforeUnmount,onMounted,reactive,ref,watch} from 'vue';
import {useRoute} from 'vue-router';
import {useDetailStore} from '../stores/detail';
import {useDashboardStore} from '../stores/dashboard';
import {useAccountStore} from '../stores/account';
import {tr} from '../i18n';
import {age,chainName,date,explorer,money,num,pct,short,usd} from '../utils/format';
import {selectDetailMarket} from '../utils/market-selection';
import {tradeKey} from '../stores/feed';
import {detailAsset,detailTrades,dexAction} from '../utils/detail-presentation';
import LiveNumber from '../components/LiveNumber.vue';
import QuoteStatus from '../components/QuoteStatus.vue';
import CandleChart from '../components/CandleChart.vue';
import RiskSummary from '../components/RiskSummary.vue';
import RelationBadge from '../components/RelationBadge.vue';
import RegistryBadge from '../components/RegistryBadge.vue';
import SpreadPanel from '../components/SpreadPanel.vue';
import AssetInsight from '../components/AssetInsight.vue';
import TradeAmount from '../components/TradeAmount.vue';
const props=defineProps({chain:{type:String,required:true},address:{type:String,required:true}});
const route=useRoute(),detail=useDetailStore(),dash=useDashboardStore(),account=useAccountStore();
const error=ref(null),copied=ref(false),now=ref(Date.now()),choice=ref(null),loading=reactive({}),sectionErrors=reactive({});
const data=computed(()=>detail.cache.get(`${props.chain}:${props.address.toLowerCase()}`)?.data??null),asset=computed(()=>detailAsset(data.value?.asset,props.chain,props.address));
const dex=computed(()=>dexAction(props.chain,props.address));
const tabs=[{key:'overview',zh:'概览',en:'Overview'},{key:'trades',zh:'成交',en:'Trades'},{key:'holders',zh:'持仓',en:'Holders'},{key:'relation',zh:'关联',en:'Relationships'}];
const activeTab=computed(()=>tabs.some(t=>t.key===route.query.tab)?route.query.tab:'overview');
const watchKey=computed(()=>`${props.chain}:${props.address.toLowerCase()}`),followed=computed(()=>account.watches.includes(watchKey.value));
const backLink=computed(()=>({path:route.query.from==='stock'?(route.query.ticker?'/stock/'+encodeURIComponent(route.query.ticker):'/stock'):route.query.from==='watch'?'/watch':route.query.from==='live'?'/live':'/meme',query:{chain:route.query.chain}})),backLabel=computed(()=>route.query.from==='stock'?tr('股票','Stocks'):route.query.from==='watch'?tr('我的关注','Watchlist'):route.query.from==='live'?tr('首页','Home'):'Meme');
const relations=computed(()=>data.value?.relations??[]),tickers=computed(()=>[...new Set([...relations.value.map(r=>r.ticker),asset.value.match?.ticker].filter(Boolean))]),hasPool=computed(()=>relations.value.some(r=>r.level==='A'&&r.status==='verified'&&r.pool));
const relationshipLabel=computed(()=>hasPool.value?tr('池子配对','Pool pairing'):asset.value.match?.level==='B'||relations.value.some(r=>r.level==='B')?tr('名称匹配','Name match'):Number(data.value?.relationCount??0)>relations.value.length?tr('查看关联栏目','See relationships'):tr('暂无股票关联','No stock relationship'));
const exchangeMarkets=computed(()=>asset.value.exchangeMarkets??data.value?.markets?.filter?.(m=>m.venue!=='dex')??[]),poolMarkets=computed(()=>data.value?.poolMarkets??asset.value.poolMarkets??data.value?.markets?.filter?.(m=>m.venue==='dex')??[]);
const marketSelection=computed(()=>selectDetailMarket(asset.value,exchangeMarkets.value,poolMarkets.value,choice.value)),selectedPoolId=computed(()=>marketSelection.value.kind==='pool'?String(marketSelection.value.pool.poolId??marketSelection.value.pool.pool??marketSelection.value.pool.marketId):'');
// Chart market selection never changes the canonical headline quote.
const chartAsset=computed(()=>marketSelection.value.kind==='exchange'?{...asset.value,...marketSelection.value.exchange,token:asset.value.token,chainId:asset.value.chainId,priceScope:'exchange'}:asset.value);
const nativePool=computed(()=>{
  // poolMarkets comes from the on-chain market registry. Require a real pool
  // address and a recent recorded trade before offering it as a live fallback.
  const candidates=poolMarkets.value.filter(p=>{
    const pool=String(p.poolId??p.pool??p.marketId??'');
    const last=Number(p.lastTradeAt);
    return p.venue==='dex' && p.quoteType==='pool' && /^0x[0-9a-f]{40}$/i.test(pool)
      && p.priceCurrency && p.priceCurrency!=='USD' && Number.isFinite(last)
      && last>0 && last<=now.value && now.value-last<=600_000;
  }).sort((a,b)=>Number(b.lastTradeAt)-Number(a.lastTradeAt));
  const best=candidates[0];
  return best?{poolId:String(best.poolId??best.pool??best.marketId),priceCurrency:String(best.priceCurrency)}:null;
});
function selectNativePool(poolId){choice.value=`pool:${poolId}`;}
const trades=computed(()=>detailTrades(data.value,marketSelection.value));
const tradeScopeLabel=computed(()=>selectedPoolId.value?tr('仅此池成交','Trades from this pool only'):marketSelection.value.kind==='exchange'?tr('仅此交易所市场成交','Trades from this exchange market only'):tr('全池最近成交；与图表市场可能不同','Recent trades across all pools; the chart may use another market'));
const chartBaseLabel=computed(()=>`${asset.value.primaryQuote?.provider??asset.value.fieldSources?.price??asset.value.provider??tr('主行情','Primary quote')} · ${asset.value.priceCurrency??'—'}`);
const holderSourceTitle=computed(()=>`${data.value?.holdersSummary?.distribution?.provider??'—'} · ${date(data.value?.holdersSummary?.distribution?.checkedAt)}`);
function tradeSourceTitle(t){return `${t.source??t.provider??t.venue??'—'} · ${date(t.t)}`;}
const tradeStatus=computed(()=>{now.value;const lag=Math.max(0,...trades.value.slice(0,1).map(t=>Number(t.delayMs??0)));return lag>30000?tr(`延迟约 ${Math.ceil(lag/1000)} 秒`,`Delayed ~${Math.ceil(lag/1000)}s`):dash.hasProjectionStream?tr('实时推送已连接','Live stream connected'):tr('定时更新','Periodic updates');});
function metricTitle(field){return `${asset.value.fieldSources?.[field]??asset.value.primaryQuote?.provider??asset.value.provider??'—'} · ${date(asset.value.fieldTimes?.[field])}`;}
let generation=0,release,timer,disposed=false;
async function loadSection(section,force=false,offset=0){const gen=generation,c=props.chain,a=props.address;loading[section]=true;sectionErrors[section]=false;try{await detail.fetchSection(c,a,section,{force,offset});}catch{if(gen===generation)sectionErrors[section]=true;}finally{if(gen===generation)loading[section]=false;}}
function loadActive(force=false){if(!data.value)return;const section=activeTab.value==='overview'?'markets':activeTab.value==='relation'?'relations':activeTab.value;loadSection(section,force);if(section==='trades')loadSection('markets',force);if(section==='markets')loadSection('trades',force);}
async function load(force=false){const gen=generation;try{await detail.fetch(props.chain,props.address,{force});if(gen!==generation||disposed)return;error.value=null;loadActive(force);}catch(e){if(gen===generation)error.value=e.message;}}
function switchAsset(){++generation;release?.();detail.watch(props.chain,props.address);release=detail.activate(props.chain,props.address);error.value=null;choice.value=route.query.pool?`pool:${route.query.pool}`:null;Object.keys(loading).forEach(k=>delete loading[k]);Object.keys(sectionErrors).forEach(k=>delete sectionErrors[k]);load();}
async function copyAddress(){try{await navigator.clipboard.writeText(props.address);copied.value=true;setTimeout(()=>copied.value=false,1500);}catch{copied.value=false;}}
function invalidate(e){const r=e.detail??{};if(r.chainId&&String(r.chainId)!==props.chain||r.token&&String(r.token).toLowerCase()!==props.address.toLowerCase())return;loadActive(true);}
function manual(){load(true);}
watch(()=>`${props.chain}:${props.address}`,switchAsset);watch(activeTab,()=>loadActive());watch(()=>route.query.pool,pool=>{choice.value=pool?`pool:${pool}`:null;});
onMounted(()=>{switchAsset();timer=setInterval(()=>{now.value=Date.now();if(!document.hidden&&(!dash.hasProjectionStream||Date.now()-(detail.cache.get(watchKey.value)?.at??0)>60000))load(true);},20000);window.addEventListener('resource-change',invalidate);window.addEventListener('manual-refresh',manual);});
onBeforeUnmount(()=>{disposed=true;++generation;release?.();detail.unwatch();clearInterval(timer);window.removeEventListener('resource-change',invalidate);window.removeEventListener('manual-refresh',manual);});
</script>
<style scoped>
.asset-overview-grid{display:grid;grid-template-columns:minmax(0,1fr) 310px;gap:16px}.asset-trade-mini{display:grid;grid-template-columns:minmax(58px,1fr) 45px minmax(118px,auto);gap:8px;align-items:center;border-bottom:1px solid var(--border);padding:15px 0;font-size:12px}.asset-trade-mini time{color:var(--muted)}.asset-trade-mini b{text-align:right}@media(max-width:1100px){.asset-overview-grid{grid-template-columns:minmax(0,1fr)}.asset-live-trades{display:block}.asset-trade-mini:nth-of-type(n+6){display:none}}
.asset-dex-action{display:inline-flex;align-items:center;justify-content:center;padding:8px 12px;border:1px solid var(--border);border-radius:5px;color:var(--text);font-size:13px}.asset-heading .panel-head{flex-wrap:wrap}.asset-heading .panel-head h2{margin-right:auto}.asset-chart-panel select{max-width:100%}.asset-page{display:grid;gap:16px}.asset-heading h2{margin:8px 0}.asset-heading small{font-size:14px;color:var(--muted)}.asset-heading button{background:var(--surface-raised);border:1px solid var(--border);color:var(--text);padding:8px 12px;border-radius:5px;cursor:pointer}.asset-heading .text-button{background:none;border:0;padding:2px;color:var(--accent)}.asset-price-line{display:flex;align-items:center;flex-wrap:wrap;gap:20px}.asset-price-line>:first-child{font-size:32px;font-weight:600;font-variant-numeric:tabular-nums}.asset-price-line small{font-size:12px;color:var(--muted)}.asset-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border:1px solid var(--border);border-radius:7px;background:var(--panel)}.asset-kpis>div{display:grid;gap:8px;padding:18px;border-right:1px solid var(--border)}.asset-kpis>div:last-child{border:0}.asset-kpis>div>span,.asset-kpis small{font-size:12px;color:var(--muted)}.asset-kpis strong{font-size:19px;font-variant-numeric:tabular-nums}.asset-tabs{display:flex;gap:28px;border-bottom:1px solid var(--border)}.asset-tabs a{padding:12px 0;border-bottom:2px solid transparent}.asset-tabs a.active{border-color:var(--accent);color:var(--text)}.asset-chart-panel{min-height:420px}.asset-facts dl>div{display:grid;grid-template-columns:130px 1fr;gap:15px;padding:10px 0;border-bottom:1px solid var(--border)}.asset-facts dt{color:var(--muted)}.asset-facts dd{margin:0}.asset-facts a{margin-right:12px}.asset-relation{padding:18px 0;border-bottom:1px solid var(--border)}.relation-flow{display:flex;gap:15px;flex-wrap:wrap}.table-wrap{overflow-x:auto}.table-wrap table{min-width:690px}@media(max-width:700px){.asset-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.asset-kpis>div{border-bottom:1px solid var(--border)}.asset-price-line>:first-child{font-size:28px}.asset-tabs{gap:22px}.asset-chart-panel .panel-head{align-items:flex-start;gap:10px;flex-direction:column}.asset-facts dl>div{grid-template-columns:100px 1fr}.asset-heading .panel-head{align-items:flex-start}.asset-kpis strong{font-size:17px}}
</style>
