<template>
  <div>
    <div class="hero x-hero">
      <div class="v2-hero-copy">
        <span class="eyebrow">STOCKSMEME / RELATIONSHIP INTELLIGENCE</span>
        <h2>{{ tr('发现股票相关 Meme，查看链上配对证据。', 'Find stock-related memes with on-chain pair evidence.') }}</h2>
      </div>
      <form id="v2Search" @submit.prevent="goSearch">
        <input v-model="q" :placeholder="tr('搜索股票、币名或合约地址', 'Search stocks, tokens or contract addresses')" required>
        <button>{{ tr('搜索', 'Search') }}</button>
      </form>
    </div>

    <div class="kpis">
      <KpiCard kpi-key="actionableAssets" :title="tr('达到流动性门槛的 Meme', 'Memes above the liquidity floor')"
        :value="num(metrics.actionableAssets)" :note="tr('已核验且新鲜池流动性 ≥ $1,000', 'Verified with fresh pool liquidity ≥ $1,000')" href="#/meme?filter=related" />
      <KpiCard kpi-key="verifiedPools" :title="tr('已确认的股票配对池', 'Confirmed stock pair pools')"
        :value="num(metrics.verifiedPools)" :note="tr('按链与池地址去重', 'Deduplicated by chain and pool')" href="#/pair/196/0x0" />
      <KpiCard kpi-key="pairedLiquidityUsd" :title="tr('已收录股票配对池流动性', 'Listed pair-pool liquidity')"
        :value="usd(metrics.pairedLiquidityUsd)"
        :note="`${num(cov.valued)} / ${num(cov.total)} ${tr('池有新鲜估值', 'pools with fresh valuations')}`" />
      <KpiCard kpi-key="newRelations24h" :title="tr('24h 新增配对', 'New pairs in 24h')"
        :value="num(metrics.newRelations24h)" :note="tr('按首次发现时间统计', 'Counted by first detection')" href="#/events" />
    </div>

    <div class="x-grid v2-overview-grid">
      <section class="panel">
        <div class="panel-head">
          <h2>{{ tr('最新发现与变化', 'Latest discoveries and changes') }}<HelpTip :title="tr('最新发现', 'Discoveries')" :body="tr('首次核验与证据变化事件，按时间倒序。', 'First-verification and evidence-change events, newest first.')" /></h2>
        </div>
        <div v-if="signals.length">
          <a v-for="ev in signals.slice(0, 8)" :key="ev.id" class="x-event" :href="detailLink({ token: ev.asset, chainId: ev.chainId ?? '196' })">
            <span class="x-event-dot"></span>
            <div>
              <strong>{{ ev.symbol ?? short(ev.asset) }} → {{ ev.ticker }}</strong>
              <p>{{ ev.label }}</p>
              <small>{{ tr('首次记录', 'First recorded') }} {{ date(ev.t) }}</small>
            </div>
            <span>{{ tr('查看证据', 'View evidence') }} ↗</span>
          </a>
        </div>
        <div v-else class="x-empty">{{ tr('正在反查股票配对池。发现并核验关系后，事件会出现在这里。', 'Tracing stock pair pools. Events appear here once a relationship is found and verified.') }}</div>
      </section>

      <section class="panel">
        <div class="panel-head">
          <h2>{{ tr('行业篮子', 'Sector baskets') }}<HelpTip :title="tr('行业篮子', 'Sector baskets')" :body="tr('固定基期 100；仅含已核验配对成分。', 'Fixed base 100; verified-pair members only.')" /></h2>
        </div>
        <div v-if="sectors.length" class="x-basket">
          <div v-for="b in sectors" :key="b.sector" class="x-basket-row">
            <span>{{ b.sector }}</span>
            <strong>{{ b.value != null ? Number(b.value).toFixed(2) : `${b.members}/3` }}</strong>
            <small>{{ b.reason }}</small>
          </div>
        </div>
        <div v-else class="x-empty">{{ tr('等待合格成分（已核验且流动性达标）。', 'Waiting for qualified verified members.') }}</div>
      </section>
    </div>

    <section class="panel x-ai">
      <h2>{{ tr('今日简报', 'Today brief') }}<HelpTip :title="tr('AI 简报', 'AI briefing')" :body="tr('由 DeepSeek 基于本站已采集字段生成，只解读已有数据，不预测价格。', 'Generated by DeepSeek from collected fields only; no price forecasts.')" /></h2>
      <div v-if="briefing" class="v2-ai-fold" :class="{ 'v2-ai-open': aiOpen }">
        <div class="v2-ai-text" v-html="aiRich(briefing.text)"></div>
        <div class="v2-ai-at">{{ tr('生成于', 'Generated at') }} {{ date(briefing.at) }}</div>
      </div>
      <div v-else class="x-empty">{{ tr('简报生成中…', 'Briefing is being generated…') }}</div>
      <button v-if="briefing" class="v2-ai-more" @click="aiOpen = !aiOpen">{{ aiOpen ? tr('收起', 'Collapse') : tr('展开全文', 'Expand') }}</button>
    </section>

    <section class="panel">
      <div class="panel-head">
        <h2>{{ tr('已核验关系 · 按交易活动排序', 'Verified relationships · sorted by activity') }}</h2>
        <RouterLink to="/meme?filter=related">{{ tr('全部关系', 'All relationships') }} →</RouterLink>
      </div>
      <div v-if="related.length">
        <a v-for="a in related.slice(0, 6)" :key="a.token" class="x-signal" :href="detailLink(a)">
          <div>
            <strong>{{ a.symbol }}</strong>
            <small>{{ a.name }} · {{ short(a.token) }} · {{ chainName(a) }}</small>
          </div>
          <div>
            <strong>{{ usd(a.volume24h) }}</strong>
            <small>{{ tr('24h 成交额', '24h volume') }} · {{ age(a.updatedAt) }}</small>
          </div>
          <span aria-hidden="true">↗</span>
        </a>
      </div>
      <div v-else class="x-empty">{{ tr('尚无已完成核验的关系。', 'No relationship has completed verification yet.') }}</div>
    </section>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import KpiCard from '../components/KpiCard.vue';
import HelpTip from '../components/HelpTip.vue';
import { useDashboardStore } from '../stores/dashboard';
import { getBriefing } from '../api/client';
import { tr, useI18n } from '../i18n';
import { age, chainName, date, detailLink, num, short, usd } from '../utils/format';

const store = useDashboardStore();
const router = useRouter();
const q = ref('');
const briefing = ref(null);
const aiOpen = ref(false);
const { lang } = useI18n();

const metrics = computed(() => store.metrics);
const cov = computed(() => metrics.value.liquidityCoverage ?? {});
const signals = computed(() => store.snapshot?.unified?.signals ?? []);
const sectors = computed(() => store.snapshot?.unified?.sectors ?? []);
const related = computed(() =>
  (store.assets ?? [])
    .filter((a) => a.kind === 'candidate' && store.relations.some((r) => r.token === a.token && r.status === 'verified'))
    .sort((a, b) => (b.volume24h ?? -1) - (a.volume24h ?? -1)),
);

function goSearch() {
  const value = q.value.trim();
  if (!value) return;
  const stocks = store.stockTokens.filter((s) =>
    [s.stockCode, s.tokenContractAddress, s.tokenSymbol].filter(Boolean).some((v) => v.toLowerCase() === value.toLowerCase()),
  );
  router.push(stocks.length ? { path: '/stock', query: { q: value } } : { path: '/meme', query: { q: value, filter: 'all' } });
}

// 【X】-> meme search link; section headings bold. Escape everything else.
function aiRich(text) {
  const esc = (s) => String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  let html = esc(text).replace(/【([^】]+)】/g, (_m, s) => `<a href="#/meme?q=${encodeURIComponent(esc(s))}">${esc(s)}</a>`);
  html = html.replace(/(今日一句话|值得看|警惕|数据边界)：?/g, '<strong>$1</strong>：');
  return html;
}

onMounted(async () => {
  getBriefing(lang.lang).then((r) => {
    if (r?.text) briefing.value = r;
  });
});
</script>
