<template>
  <div>
    <div class="hero x-hero">
      <div class="v2-hero-copy">
        <span class="eyebrow">STOCKSMEME / RELATIONSHIP INTELLIGENCE</span>
        <h2>{{ tr('发现股票相关 Meme，查看链上配对证据。', 'Find stock-related memes with on-chain pair evidence.') }}
          <HelpTip :title="tr('总览', 'Overview')" :body="tr('从已核验配对出发观察股票相关 Meme 市场。', 'Observe the stock-related meme market through verified pairs.')" />
        </h2>
      </div>
      <form id="v2Search" @submit.prevent="goSearch">
        <input v-model="q" :placeholder="tr('搜索股票、币名或合约地址', 'Search stocks, tokens or contract addresses')" required>
        <button>{{ tr('搜索', 'Search') }}</button>
      </form>
    </div>

    <section class="panel x-ai">
      <h2>{{ tr('今日变化摘要', 'Today changes') }}</h2>
      <p class="hint">{{ tr('由 DeepSeek 基于本站已采集字段生成，只解读已有数据，不预测价格。', 'Generated by DeepSeek from collected fields only; no price forecasts.') }}</p>
      <div v-if="briefing" class="v2-ai-fold" :class="{ 'v2-ai-open': aiOpen }">
        <div class="v2-ai-text" v-html="aiRich(briefing.text)"></div>
        <div class="v2-ai-at">{{ tr('生成于', 'Generated at') }} {{ date(briefing.at) }}</div>
      </div>
      <div v-else class="v2-ai-text">{{ tr('简报生成中…', 'Briefing is being generated…') }}</div>
      <button v-if="briefing" class="v2-ai-more" @click="aiOpen = !aiOpen">{{ aiOpen ? tr('收起', 'Collapse') : tr('展开全文', 'Expand') }}</button>
    </section>

    <div class="kpis">
      <KpiCard kpi-key="actionableAssets" :title="tr('达到流动性门槛的 Meme', 'Memes above the liquidity floor')"
        :value="num(metrics.actionableAssets)" :note="tr('已核验且新鲜池流动性 ≥ $1,000', 'Verified with fresh pool liquidity ≥ $1,000')" href="#/meme?filter=related" />
      <KpiCard kpi-key="verifiedPools" :title="tr('已确认的股票配对池', 'Confirmed stock pair pools')"
        :value="num(metrics.verifiedPools)" :note="tr('按链与池地址去重', 'Deduplicated by chain and pool')" href="#/pair" />
      <KpiCard kpi-key="pairedLiquidityUsd" :title="tr('已收录股票配对池流动性', 'Listed pair-pool liquidity')"
        :value="usd(metrics.pairedLiquidityUsd)"
        :note="`${num(cov.valued)} / ${num(cov.total)} ${tr('池有新鲜估值', 'pools with fresh valuations')} · ${tr('覆盖数量变化不等于资金进出', 'coverage changes are not flows')}`" />
      <KpiCard kpi-key="newRelations24h" :title="tr('24h 新增配对', 'New pairs in 24h')"
        :value="num(metrics.newRelations24h)" :note="tr('按首次发现时间统计', 'Counted by first detection')" href="#/events" />
    </div>

    <div class="x-grid v2-overview-grid">
      <section class="panel">
        <div class="panel-head">
          <h2>{{ tr('最新发现与变化', 'Latest discoveries and changes') }}<HelpTip :title="tr('最新发现', 'Discoveries')" :body="tr('首次核验与证据变化事件，按时间倒序。', 'First-verification and evidence-change events, newest first.')" /></h2>
          <RouterLink to="/events">{{ tr('全部历史', 'Full history') }} →</RouterLink>
        </div>
        <div v-if="signals.length">
          <EventRow v-for="ev in signals.slice(0, 6)" :key="ev.id" :ev="ev" />
        </div>
        <div v-else class="x-empty">{{ tr('尚无关系变化，采集继续运行。', 'No relationship changes yet; collection continues.') }}</div>
      </section>

      <section class="panel">
        <div class="panel-head">
          <h2>{{ tr('关联 Meme 成交榜', 'Related-meme volume') }}<HelpTip :title="tr('成交榜', 'Volume')" :body="tr('已核验配对资产按 24h 成交额排序。', 'Verified-pair assets ranked by 24h volume.')" /></h2>
          <RouterLink to="/meme?filter=related">{{ tr('全部', 'All') }} →</RouterLink>
        </div>
        <div v-if="related.length">
          <RouterLink v-for="a in related.slice(0, 6)" :key="a.token" class="x-signal" :to="{ path: '/meme', query: { q: a.symbol } }">
            <span class="v2-asset-identity">{{ a.symbol }}</span>
            <span>{{ relatedTickers(a) }}</span>
            <span>{{ usd(a.volume24h) }}<small>24h · {{ chainName(a) }}</small></span>
          </RouterLink>
        </div>
        <div v-else class="x-empty">{{ tr('等待可核查的配对证据', 'Waiting for verifiable pair evidence') }}</div>
      </section>
    </div>

    <section class="panel">
      <h2>{{ tr('行业主题指数', 'Sector theme indices') }}<HelpTip :title="tr('行业指数', 'Sector indices')" :body="tr('固定基期 100、固定成分与市值权重。行情过期不删除成分；缺口不补画。', 'Fixed base 100, constituents and market-cap weights. Stale prices do not remove members; gaps are not backfilled.')" /></h2>
      <p class="hint">{{ tr('固定基期 100、固定成分与市值权重。行情过期不删除成分；缺口不补画。', 'Fixed base 100, constituents and market-cap weights. Stale prices do not remove members; gaps are not backfilled.') }}</p>
      <div class="v2-baskets">
        <details v-for="s in liveSectors" :key="s.sector" class="x-basket">
          <summary>
            <strong>{{ s.sector }}</strong>
            <span>{{ s.value != null ? num(s.value) : tr('收集成分中', 'Collecting members') }}</span>
            <small>{{ s.chainId ?? '196' }} · {{ s.members }}/3 {{ tr('成分门槛', 'minimum members') }}</small>
          </summary>
          <p>{{ s.value != null ? tr('当前指数', 'Current index') : tr('等待合格成分或新鲜行情', 'Waiting for eligible members or fresh prices') }} · {{ date(s.baseAt) }}</p>
          <p v-for="c in s.components ?? []" :key="c.token">
            <RouterLink :to="{ path: '/detail/' + (s.chainId ?? '196') + '/' + c.token }">{{ c.symbol }}</RouterLink>
            {{ c.weight != null ? pct(c.weight * 100) : '' }}
          </p>
        </details>
      </div>
      <p v-if="pendingSectors" class="hint">{{ tr('另有', '') }} {{ pendingSectors }} {{ tr('个行业主题筹备中，达到成分门槛后发布，不虚构指数。', 'sector themes in preparation; published only when eligible, no synthetic index.') }}</p>
      <div v-else-if="!sectors.length" class="x-empty">{{ tr('暂无行业篮子数据', 'No basket data yet') }}</div>
    </section>

    <section class="panel">
      <h2>{{ tr('各链数据概况', 'Chain overview') }}<HelpTip :title="tr('链概况', 'Chains')" :body="tr('仅汇总新鲜且同口径的链上数据；场内成交不加入。', 'Only fresh, comparable on-chain data is aggregated; exchange volume is excluded.')" /></h2>
      <RouterLink v-for="d in distribution" :key="d.chainId" class="v2-distribution" :to="{ path: '/meme', query: { filter: 'all', chain: d.chainId } }">
        <strong>{{ d.name }}</strong>
        <span>{{ num(d.assets) }} {{ tr('已发现候选', 'discovered candidates') }}</span>
        <span>24h {{ usd(d.volume?.value) }} <small>{{ d.volume?.known }}/{{ d.assets }} {{ tr('有值', 'available') }}</small></span>
        <span>{{ tr('池流动性', 'Pool liquidity') }} {{ usd(d.liquidity?.value) }}</span>
      </RouterLink>
    </section>

    <p class="v2-sources-line">{{ tr('数据来源：OKX RWA API · 三链 RPC 直读（BNB / X Layer / Robinhood Chain）· GeckoTerminal / DexScreener 行情 · Binance / Robinhood 公开接口。每个数字标注采集时间，缺失如实标注，不用旧数据冒充实时。', 'Sources: OKX RWA API · direct RPC on three chains (BNB / X Layer / Robinhood Chain) · GeckoTerminal / DexScreener quotes · Binance / Robinhood public APIs. Every number carries its observation time; missing stays missing.') }}</p>
  </div>
</template>

<script setup>
import { computed, onMounted, ref, watch } from 'vue';
import { useRouter } from 'vue-router';
import KpiCard from '../components/KpiCard.vue';
import HelpTip from '../components/HelpTip.vue';
import EventRow from '../components/EventRow.vue';
import { useDashboardStore } from '../stores/dashboard';
import { getBriefing } from '../api/client';
import { tr, useI18n } from '../i18n';
import { chainName, date, num, pct, usd } from '../utils/format';

const store = useDashboardStore();
const router = useRouter();
const q = ref('');
const briefing = ref(null);
const aiOpen = ref(false);
const { lang } = useI18n();

const metrics = computed(() => store.metrics);
const cov = computed(() => metrics.value.liquidityCoverage ?? {});
const signals = computed(() => store.snapshot?.unified?.signals ?? []);
const sectors = computed(() => store.snapshot?.unified?.sectors ?? []);
const distribution = computed(() => store.snapshot?.unified?.distribution ?? []);
const liveSectors = computed(() => sectors.value.filter((s) => s.lastValue != null || s.value != null));
const pendingSectors = computed(() => sectors.value.filter((s) => s.lastValue == null && s.value == null).length);
const related = computed(() =>
  (store.assets ?? [])
    .filter((a) => a.kind === 'candidate' && store.relations.some((r) => r.token === a.token && r.status === 'verified'))
    .sort((a, b) => (b.volume24h ?? -1) - (a.volume24h ?? -1)),
);

function relatedTickers(a) {
  return store.relations.filter((r) => r.token === a.token && r.status === 'verified').map((r) => r.ticker).join(' / ');
}

function goSearch() {
  const value = q.value.trim();
  if (!value) return;
  const stocks = store.stockTokens.filter((s) =>
    [s.stockCode, s.tokenContractAddress, s.tokenSymbol].filter(Boolean).some((v) => v.toLowerCase() === value.toLowerCase()),
  );
  router.push(stocks.length ? { path: '/stock', query: { q: value } } : { path: '/meme', query: { q: value, filter: 'all' } });
}

function aiRich(text) {
  const esc = (s) => String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  let html = esc(text).replace(/【([^】]+)】/g, (_m, s) => `<a href="#/meme?q=${encodeURIComponent(esc(s))}">${esc(s)}</a>`);
  html = html.replace(/(今日一句话|值得看|警惕|数据边界)：?/g, '<strong>$1</strong>：');
  return html;
}

async function loadBriefing() {
  briefing.value = null;
  const r = await getBriefing(lang.lang);
  if (r?.text) briefing.value = r;
}

onMounted(loadBriefing);
watch(() => lang.lang, loadBriefing);
</script>
