import sqlite3
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from app.aux_storage_schema import TELEGRAM_TABLES, declared_account_tables, install_standby_account_auxiliary_schema
from app.storage_migration import target_ddl, target_index_ddl


class AuxiliarySchemaTests(unittest.TestCase):
    def test_account_runtime_schema_retains_six_explicit_telegram_tables(self):
        # Extraction must not invoke account initialization against the user's
        # credentials file; only a throwaway SQLite in-memory schema is used.
        with patch('app.developer_access.init', side_effect=AssertionError('runtime account access')):
            declarations = declared_account_tables()
        self.assertEqual(len(declarations), 23)
        self.assertEqual({name for name in declarations if name.startswith('telegram_')}, set(TELEGRAM_TABLES))
        for name in TELEGRAM_TABLES:
            ddl = target_ddl(declarations[name])
            self.assertIn('_cliperx_source_rowid BIGINT GENERATED BY DEFAULT AS IDENTITY', ddl)
            self.assertIn('CREATE TABLE', ddl)
        outbox = target_ddl(declarations['telegram_outbox'])
        self.assertIn('REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED', outbox)
        self.assertIn('UNIQUE ("user_id", "binding_id", "event_key")', outbox)
        self.assertEqual(len(declarations['telegram_outbox']['indexes']), 2)
        for statement in declarations['telegram_outbox']['indexes']:
            self.assertIn('CREATE INDEX', target_index_ddl(statement))

    def test_standby_extra_tables_preserve_original_schema_rows_and_foreign_keys(self):
        declarations = declared_account_tables()
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / 'accounts.sqlite'
            with sqlite3.connect(path) as connection:
                for name, table in declarations.items():
                    if name not in TELEGRAM_TABLES:
                        connection.execute(table['sql'])
                        for index in table['indexes']:
                            connection.execute(index)
                connection.execute('INSERT INTO users VALUES (?,?,?,?,?,NULL)', ('u', 'test@example.com', b'salt', b'hash', 123))
                original_schema = list(connection.execute("SELECT name,sql FROM sqlite_master WHERE type='table' ORDER BY name"))
            result = install_standby_account_auxiliary_schema(path)
            self.assertEqual(set(result['installedTables']), set(TELEGRAM_TABLES))
            self.assertEqual(len(result['installedIndexes']), 3)
            self.assertEqual(install_standby_account_auxiliary_schema(path)['installedTables'], [])
            with sqlite3.connect(path) as connection:
                self.assertEqual(connection.execute('SELECT * FROM users').fetchall(), [('u', 'test@example.com', b'salt', b'hash', 123, None)])
                remaining_schema = list(connection.execute("SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'telegram_%' ORDER BY name"))
                self.assertEqual(remaining_schema, original_schema)
                for name in TELEGRAM_TABLES:
                    self.assertEqual(connection.execute('SELECT count(*) FROM ' + name).fetchone()[0], 0)
                connection.execute('PRAGMA foreign_keys=ON')
                with self.assertRaises(sqlite3.IntegrityError):
                    connection.execute('INSERT INTO telegram_bindings VALUES (?,?,?,?,?,?)', ('missing', 'binding', 'chat', 'bot', 1, 123))
                connection.execute('INSERT INTO telegram_runtime VALUES (?,?,?)', ('test', '{}', 123))
            with self.assertRaisesRegex(ValueError, 'not-empty:telegram_runtime'):
                install_standby_account_auxiliary_schema(path)
            with sqlite3.connect(path) as connection:
                self.assertEqual(connection.execute('SELECT value FROM telegram_runtime WHERE key=?', ('test',)).fetchone()[0], '{}')


if __name__ == '__main__':
    unittest.main()
