import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {parse,compileScript} from '@vue/compiler-sfc';
import * as vue from 'vue';
import * as vueRouter from 'vue-router';
import * as format from '../src/utils/format.js';
import * as chains from '../src/utils/chain-scope.js';
import * as navigation from '../src/utils/navigation-context.js';
import * as labels from '../src/utils/product-labels.js';
import * as quoteStatus from '../src/utils/quote-status.js';
import * as themes from '../src/utils/stock-theme-model.js';
import * as stockRefresh from '../src/utils/stock-directory-refresh.js';
import * as eventModel from '../src/utils/event-records.js';
import * as exchange from '../src/utils/visible-exchange-quote.js';
import * as watchModel from '../src/utils/watch-model.js';
const token='0x'+'a'.repeat(40),other='0x'+'b'.repeat(40),key=`56:${token}`;
const tick=async()=>{for(let i=0;i<6;i++){await Promise.resolve();await vue.nextTick();}await new Promise(resolve=>setTimeout(resolve,0));await vue.nextTick();};
const defer=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const asset=(price=2,at=Date.now()-20000)=>({chainId:'56',token,name:'Coin',symbol:'COIN',price,priceCurrency:'USD',priceScope:'token',provider:'OKX',fieldSources:{price:'OKX'},fieldScopes:{price:'token'},fieldTimes:{price:at},quoteAt:at});
const item=(price=2)=>({key,kind:'asset',chainId:'56',token,asset:asset(price)});
const packet=items=>({items,snapshotAt:Date.now(),realtime:{cursor:10,revision:10},directory:{total:items.length}});
const event=(id,t=Date.now(),extra={})=>({id,chainId:'56',asset:token,symbol:id,t,ticker:'700',kind:'verified',...extra});
async function mount({watches=[],summary=async()=>packet([item()]),events=async()=>({items:[],hasMore:false}),query={chain:'all'},session=null,ready=true}={}){
  const saved={Document:globalThis.Document,ShadowRoot:globalThis.ShadowRoot,document:globalThis.document};
  globalThis.Document??=class Document{};globalThis.ShadowRoot??=class ShadowRoot{};
  const listeners=new Map();globalThis.document={hidden:false,addEventListener:(key,fn)=>listeners.set(key,fn),removeEventListener:key=>listeners.delete(key)};
  const account=vue.reactive({watches,session,ready,syncState:session?'synced':'local',starts:0,start(){this.starts++;},refresh(){},toggle(value){this.watches=this.watches.includes(value)?this.watches.filter(k=>k!==value):[...this.watches,value];}});
  const router=vueRouter.createRouter({history:vueRouter.createMemoryHistory(),routes:['/watch','/me','/meme','/stock','/stock/:ticker','/asset/:chain/:address'].map(path=>({path,component:{render:()=>null}}))});await router.push({path:'/watch',query});
  const language=vue.reactive({lang:'zh'}),calls={summary:[],events:[]};let live;
  const stub={render:()=>vue.h('span')};
  const imports={vue,'vue-router':vueRouter,'../stores/account':{useAccountStore:()=>account},'../api/watch':{getWatchSummary:(body,options)=>{calls.summary.push({body,options});return summary(body,options);},getWatchEvents:(body,options)=>{calls.events.push({body,options});return events(body,options);}},
    '../composables/useVisibleQuotes':{useVisibleQuotes:options=>{live=options;return {status:vue.reactive({connected:true,state:'connected'})};}},'../i18n':{tr:(zh,en)=>language.lang==='en'?en:zh,useI18n:()=>({lang:language})},'../utils/format':format,'../utils/chain-scope':chains,'../utils/navigation-context':navigation,'../utils/product-labels':labels,'../utils/quote-status':quoteStatus,'../utils/stock-theme-model':themes,'../utils/stock-directory-refresh':stockRefresh,'../utils/event-records':eventModel,'../utils/visible-exchange-quote':exchange,'../utils/watch-model':watchModel,
    '../components/LiveNumber.vue':{props:['value','currency'],setup:props=>()=>vue.h('span',props.value==null?'—':String(props.value)+' '+(props.currency??''))},
    '../components/LiveDataStatus.vue':{props:['quoteAt'],emits:['refresh'],setup:(props,{emit})=>()=>vue.h('div',{'data-live-status':true},[vue.h('span',String(props.quoteAt)),vue.h('button',{onClick:()=>emit('refresh')},'Refresh')])},'../components/KolTracker.vue':stub,'../components/SignalLegend.vue':stub,'../components/RiskBadge.vue':stub,'../components/QuoteStatus.vue':{props:['row'],setup:props=>()=>vue.h('small',props.row?.provider??'')}};
  const compiled=compileScript(parse(readFileSync(new URL('../src/views/WatchView.vue',import.meta.url),'utf8')).descriptor,{id:'watch',inlineTemplate:true}).content.replace(/^import\s+\{([^}]+)\}\s+from\s+['"]([^'"]+)['"];?\s*$/gm,(_,bindings,path)=>`const {${bindings.replace(/\s+as\s+/g,':')}}=imports[${JSON.stringify(path)}];`).replace(/^import\s+(\w+)\s+from\s+['"]([^'"]+)['"];?\s*$/gm,(_,name,path)=>`const ${name}=imports[${JSON.stringify(path)}];`).replace('export default','return');
  imports['../components/AssetAvatar.vue']={render:()=>null};
  const component=new Function('imports',compiled)(imports);
  const node=(type,text='')=>({type,text,props:{},children:[],parent:null,listeners:new Map(),value:'',selected:false,style:{},addEventListener(key,fn){this.listeners.set(key,fn);},removeEventListener(key){this.listeners.delete(key);},getRootNode(){return {};},get options(){return this.children.filter(child=>child.type==='option');}});
  const detach=child=>{if(child.parent){const at=child.parent.children.indexOf(child);if(at>=0)child.parent.children.splice(at,1);child.parent=null;}};
  const renderer=vue.createRenderer({createElement:tag=>node(tag),createText:text=>node('text',text),createComment:()=>node('comment'),insert:(child,parent,anchor)=>{detach(child);child.parent=parent;const at=anchor?parent.children.indexOf(anchor):-1;if(at<0)parent.children.push(child);else parent.children.splice(at,0,child);},remove:detach,setText:(target,text)=>target.text=text,setElementText:(target,text)=>{target.text=text;target.children=[];},patchProp:(target,k,_old,value)=>{target.props[k]=value;if(k==='value'){target.value=value;target._value=value;}},parentNode:target=>target.parent,nextSibling:target=>target.parent?.children[target.parent.children.indexOf(target)+1]??null});
  const root=node('root'),app=renderer.createApp({render:()=>vue.h(component)});app.use(router);app.mount(root);await tick();
  const textOf=target=>target.text+target.children.map(textOf).join('');
  const all=()=>{const out=[];const visit=target=>{out.push(target);target.children.forEach(visit);};visit(root);return out;};
  const find=(type,label)=>all().find(target=>target.type===type&&textOf(target)===label);
  const byClass=label=>all().find(target=>String(target.props.class??'').split(' ').includes(label));
  async function click(type,label){const target=find(type,label);assert.ok(target,`${type}: ${label}`);await target.props.onClick({button:0,defaultPrevented:false,preventDefault(){}});await tick();}
  return {account,router,language,calls,all,text:()=>textOf(root),find,byClass,click,live:()=>live,listeners,unmount(){app.unmount();for(const name of Object.keys(saved)){if(saved[name]===undefined)delete globalThis[name];else globalThis[name]=saved[name];}}};
}

test('empty saved watchlist immediately offers both browse paths with no market or watch request',async()=>{const env=await mount({ready:false});try{assert.equal(env.calls.summary.length,0);assert.equal(env.calls.events.length,0);assert.match(env.text(),/浏览股票主题/);assert.match(env.text(),/浏览 Meme/);assert.match(env.text(),/正在检查账号/);assert.equal(env.all().some(n=>String(n.props.class).includes('watch-overview')),false);assert.equal(env.account.starts,1);}finally{env.unmount();}});
test('saved identities remain visible through account loading and a summary failure; retry is local',async()=>{let fail=true;const env=await mount({watches:[key],summary:async()=>{if(fail)throw new Error('network');return packet([item()]);},ready:false});try{assert.match(env.text(),/0xaaaa/);assert.match(env.text(),/已保存的关注仍在/);fail=false;await env.click('button','重试行情');assert.match(env.text(),/Coin/);assert.equal(env.calls.summary.length,2);}finally{env.unmount();}});
test('default activity covers all identities; selecting exact asset and clearing keeps contextual detail navigation',async()=>{const env=await mount({watches:[key,'stock:700'],events:async body=>({items:body.keys.length===1?[event('asset')]:[event('asset'),event('theme',Date.now()-1000,{asset:other,ticker:'700'})],hasMore:false})});try{assert.deepEqual(env.calls.events[0].body.keys,[key,'stock:700']);assert.match(env.text(),/全部关注动态/);await env.click('button','动态');assert.deepEqual(env.calls.events.at(-1).body.keys,[key]);assert.match(env.text(),/动态 · Coin/);await env.click('button','清除对象筛选');assert.deepEqual(env.calls.events.at(-1).body.keys,[key,'stock:700']);const link=env.find('a','CoinMeme · BNB Chain · 0xaaaa…aaaa');assert.ok(link);await link.props.onClick({button:0,defaultPrevented:false,preventDefault(){}});await tick();assert.equal(env.router.currentRoute.value.path,`/asset/56/${token}`);assert.equal(env.router.currentRoute.value.query.from,'watch');assert.match(env.router.currentRoute.value.query.back,/^\/watch/);}finally{env.unmount();}});
test('server search, kind, sort and pagination are explicit and old query responses cannot overwrite',async()=>{const wait=defer();let first=true;const env=await mount({watches:[key],summary:async body=>{if(first){first=false;return wait.promise;}return { ...packet([item(4)]),directory:{total:45} };}});try{await env.router.push({path:'/watch',query:{chain:'56',q:'Coin',kind:'asset',sort:'change24h',filter:'quote',page:'2'}});await tick();const body=env.calls.summary.at(-1).body;assert.equal(body.chain,'56');assert.equal(body.q,'Coin');assert.equal(body.kind,'asset');assert.equal(body.sort,'change24h');assert.equal(body.quoteFilter,'quote');assert.equal(body.offset,20);assert.equal(body.limit,20);wait.resolve(packet([item(1)]));await tick();assert.match(env.text(),/4 USD/);assert.doesNotMatch(env.text(),/1 USD/);await env.click('button','下一页');assert.equal(env.calls.summary.at(-1).body.offset,40);}finally{env.unmount();}});
test('foreground summaries immediately replace order while newer source-timed quotes survive',async()=>{let reversed=false;const b={key:`56:${other}`,kind:'asset',chainId:'56',token:other,asset:{...asset(3),token:other,name:'Other'}};const env=await mount({watches:[key,b.key],summary:async()=>packet(reversed?[b,item(4)]:[item(),b])});try{for(const name of ['onPointerenter','onFocusin','onTouchstartPassive','onWheelPassive'])assert.equal(env.byClass('watch-main').props[name],undefined);assert.equal(env.live().onQuote({...asset(9,Date.now()-10)}),true);await tick();reversed=true;await env.click('button','Refresh');assert.deepEqual(env.all().filter(n=>n.props['data-navigation-anchor']).map(n=>n.props['data-navigation-anchor']),[b.key,key]);assert.match(env.text(),/9 USD/);assert.equal(env.find('button','Apply rows'),undefined);}finally{env.unmount();}});
test('new events appear immediately without duplicates and preserve historical pagination cursor',async()=>{let newest=false;const historyCursor={t:100,id:'old'};const env=await mount({watches:[key],events:async body=>body.cursor?{items:[event('history',50)],hasMore:false,nextCursor:null}:{items:newest?[event('new',200),event('old',100)]:[event('old',100)],hasMore:true,nextCursor:newest?{t:200,id:'new'}:historyCursor}});try{assert.equal(env.byClass('watch-activity').props.onPointerenter,undefined);newest=true;await env.click('button','Refresh');await env.click('button','Refresh');assert.doesNotMatch(env.text(),/条新动态/);assert.equal(env.all().filter(n=>String(n.props.class).includes('watch-event-entry')).length,2);await env.click('button','读取更多记录');assert.deepEqual(env.calls.events.at(-1).body.cursor,historyCursor);assert.match(env.text(),/history/);assert.match(env.text(),/new/);}finally{env.unmount();}});
test('unfollow can be undone and switching accounts rejects stale personal activity',async()=>{const late=defer();let first=true;const env=await mount({watches:[key],session:{user:{id:'first'}},events:async()=>{if(first){first=false;return late.promise;}return {items:[event('second')],hasMore:false};}});try{env.account.session={user:{id:'second'}};await tick();late.resolve({items:[event('first')],hasMore:false});await tick();assert.match(env.text(),/second/);assert.doesNotMatch(env.text(),/first/);const remove=env.all().find(n=>n.props['aria-label']==='取消关注 Coin');assert.ok(remove);remove.props.onClick();await tick();assert.deepEqual(env.account.watches,[]);await env.click('button','撤销');assert.deepEqual(env.account.watches,[key]);}finally{env.unmount();}});
test('hidden page aborts requests; return immediately refreshes both and only subscriptions in visible list',async()=>{const wait=defer();let block=false;const env=await mount({watches:[key],summary:async()=>block?wait.promise:packet([item()])});try{assert.equal(env.live().rows.value.length,1);block=true;env.find('button','Refresh').props.onClick();await tick();const request=env.calls.summary.at(-1);document.hidden=true;env.listeners.get('visibilitychange')();assert.equal(request.options.signal.aborted,true);assert.equal(env.live().enabled.value,false);const counts=[env.calls.summary.length,env.calls.events.length];block=false;document.hidden=false;env.listeners.get('visibilitychange')();await tick();assert.equal(env.calls.summary.length,counts[0]+1);assert.equal(env.calls.events.length,counts[1]+1);assert.equal(env.live().enabled.value,true);wait.resolve(packet([item(99)]));await tick();assert.doesNotMatch(env.text(),/99 USD/);}finally{env.unmount();}});
test('language switches all watch controls and labels without re-querying private identities',async()=>{const env=await mount({watches:[key]});try{const count=env.calls.summary.length;env.language.lang='en';await tick();for(const label of ['Watchlist','Search follows','Exact assets','All followed activity','Load more records','Site-wide KOL']){if(label==='Load more records')continue;assert.match(env.text(),new RegExp(label));}assert.equal(env.calls.summary.length,count);}finally{env.unmount();}});
test('foreground activity checks every 10s and summaries every 30s; both timers stop doing work in background',async t=>{const timers=[];t.mock.method(globalThis,'setInterval',(fn,ms)=>{timers.push({fn,ms});return 999;});const env=await mount({watches:[key]});try{const activity=timers.find(timer=>timer.ms===10000),summary=timers.find(timer=>timer.ms===30000);assert.ok(activity);assert.ok(summary);const before=[env.calls.summary.length,env.calls.events.length];activity.fn();await tick();summary.fn();await tick();assert.equal(env.calls.events.length,before[1]+1);assert.equal(env.calls.summary.length,before[0]+1);document.hidden=true;env.listeners.get('visibilitychange')();const hiddenCounts=[env.calls.summary.length,env.calls.events.length];activity.fn();summary.fn();await tick();assert.deepEqual([env.calls.summary.length,env.calls.events.length],hiddenCounts);}finally{env.unmount();}});
test('two head gaps retain separate cursors so burst activity is still reachable and older history is not overwritten',async()=>{let phase=0;const cursor=t=>({t,id:String(t)});const env=await mount({watches:[key],events:async body=>{if(body.cursor?.t===200)return {items:[event('gap-200',200),event('old',100)],hasMore:true,nextCursor:cursor(100)};if(body.cursor?.t===400)return {items:[event('gap-400',400),event('new-300',300)],hasMore:true,nextCursor:cursor(300)};if(body.cursor?.t===100)return {items:[event('history',50)],hasMore:false};return {items:[event(phase===0?'old':phase===1?'new-300':'new-500',phase===0?100:phase===1?300:500)],hasMore:true,nextCursor:cursor(phase===0?100:phase===1?200:400)};}});try{phase=1;await env.click('button','Refresh');phase=2;await env.click('button','Refresh');await env.click('button','读取更多记录');assert.equal(env.calls.events.at(-1).body.cursor.t,200);await env.click('button','读取更多记录');assert.equal(env.calls.events.at(-1).body.cursor.t,400);await env.click('button','读取更多记录');assert.equal(env.calls.events.at(-1).body.cursor.t,100);for(const id of ['gap-200','gap-400','history'])assert.match(env.text(),new RegExp(id));}finally{env.unmount();}});
test('touch does not suspend updates, filter commits immediately, and theme never claims equity price',async()=>{let reverse=false;const theme={key:'stock:700',kind:'theme',ticker:'700',asset:{...asset(99),tokenContractAddress:token,stockIdentity:{code:'700',nameZh:'腾讯控股'}},theme:{theme:{pairedCount:1,volume:{value:10,known:1,total:1}},equity:{stockPrice:888,referenceCurrency:'HKD'}}};const env=await mount({watches:[key,'stock:700'],summary:async body=>body.kind==='theme'?packet([theme]):packet(reverse?[theme,item()]:[item(),theme])});try{assert.equal(env.byClass('watch-main').props.onTouchstartPassive,undefined);reverse=true;await env.click('button','Refresh');assert.deepEqual(env.all().filter(n=>n.props['data-navigation-anchor']).map(n=>n.props['data-navigation-anchor']),['stock:700',key]);await env.router.push({path:'/watch',query:{chain:'all',kind:'theme'}});await tick();assert.deepEqual(env.all().filter(n=>n.props['data-navigation-anchor']).map(n=>n.props['data-navigation-anchor']),['stock:700']);assert.match(env.text(),/股票代币参考价/);assert.doesNotMatch(env.text(),/888/);assert.match(env.text(),/配对池成交/);}finally{env.unmount();}});
test('history overlapping live activity renders each identity once through subsequent refreshes',async()=>{let phase=0;const cursor='opaque-history';const env=await mount({watches:[key],events:async body=>body.cursor?{items:[event('new',200),event('history',50)],hasMore:false}:{items:phase?[event('new',200),event('old',100)]:[event('old',100)],hasMore:true,nextCursor:cursor}});try{phase=1;await env.click('button','Refresh');assert.equal(env.all().filter(n=>String(n.props.class).includes('watch-event-entry')).length,2);await env.click('button','读取更多记录');assert.doesNotMatch(env.text(),/条新动态/);assert.equal(env.all().filter(n=>String(n.props.class).includes('watch-event-entry')).length,3);await env.click('button','Refresh');assert.equal(env.all().filter(n=>String(n.props.class).includes('watch-event-entry')).length,3);}finally{env.unmount();}});
test('unsupported saved chain remains a safe placeholder while theme uses published translated company names',async()=>{const unsupportedKey=`1:${other}`,theme={key:'stock:CUSTOM',kind:'theme',ticker:'CUSTOM',nameZh:'已核对公司名',nameEn:'Verified company name',asset:null,theme:null};const env=await mount({watches:[unsupportedKey,'stock:CUSTOM'],summary:async()=>packet([{key:unsupportedKey,kind:'asset',chainId:'1',token:other,status:'unsupported-chain',asset:null},theme])});try{assert.match(env.text(),/此链行情暂不支持，关注仍保留/);assert.match(env.text(),/网络 1/);assert.match(env.text(),/已核对公司名/);assert.equal(env.calls.summary[0].body.keys[0],unsupportedKey);env.language.lang='en';await tick();assert.match(env.text(),/Verified company name/);assert.match(env.text(),/Quotes on this chain are unsupported/);}finally{env.unmount();}});

test('scheduled polls insert new rows and new events without any manual action',async t=>{const timers=[];t.mock.method(globalThis,'setInterval',(fn,ms)=>{timers.push({fn,ms});return 999;});let changed=false;const b={key:`56:${other}`,kind:'asset',chainId:'56',token:other,asset:{...asset(3),token:other,name:'Other'}};const env=await mount({watches:[key,b.key],summary:async()=>packet(changed?[b,item()]:[item()]),events:async()=>({items:changed?[event('live-new',200),event('old',100)]:[event('old',100)],hasMore:false})});try{changed=true;timers.find(timer=>timer.ms===30000).fn();timers.find(timer=>timer.ms===10000).fn();await tick();assert.deepEqual(env.all().filter(n=>n.props['data-navigation-anchor']).map(n=>n.props['data-navigation-anchor']),[b.key,key]);assert.equal(env.all().filter(n=>String(n.props.class).includes('watch-event-entry')).length,2);assert.match(env.text(),/live-new/);assert.equal(env.find('button','Apply rows'),undefined);assert.doesNotMatch(env.text(),/正在阅读|条新动态/);}finally{env.unmount();}});
