<template>
  <details class="alias-review" @toggle="$event.target.open && load()"><summary>{{ tr('名称线索审核','Review name clues') }}</summary><p>{{ tr('只作为名称线索，不作为链上配对。未确认的候选不进入统计。','Names are clues to review. Unconfirmed candidates do not enter statistics or become pool evidence.') }}</p><form @submit.prevent="propose"><label>{{ tr('股票代号','Stock ticker') }}<input v-model.trim="ticker" maxlength="24" required></label><label>{{ tr('币名或描述原文','Original name or description') }}<input v-model.trim="sourceText" maxlength="600" required></label><label>{{ tr('建议别名（留空时请求模型）','Proposed alias (blank for model suggestion)') }}<input v-model.trim="alias" maxlength="60"></label><button :disabled="busy">{{ tr('提交候选','Propose alias') }}</button></form><p v-if="error" role="alert">{{ error }}</p><article v-for="item in items" :key="item.id"><div><strong>{{ item.ticker }} · {{ item.alias }}</strong><small>{{ item.evidence }} · {{ item.source==='model'?tr('模型候选','Model candidate'):tr('手动候选','Manual candidate') }}</small><span>{{ statusLabel(item.status) }}</span></div><div><button v-if="item.status!=='confirmed'" :disabled="busy" @click="review(item.id,true)">{{ tr('确认','Confirm') }}</button><button v-if="item.status!=='rejected'" :disabled="busy" @click="review(item.id,false)">{{ item.status==='confirmed'?tr('撤销','Revoke'):tr('拒绝','Reject') }}</button></div></article><button :disabled="busy" @click="backtest">{{ tr('运行名称回测','Run name backtest') }}</button><p v-if="score">{{ tr('样本','Samples') }} {{ score.sampleCount }} · {{ tr('精确率','Precision') }} {{ percent(score.precision) }} · {{ tr('召回率','Recall') }} {{ percent(score.recall) }}</p></details>
</template>
<script setup>
import {ref} from 'vue';
import {tr} from '../i18n';
import {productRequest} from '../api/developer';
import {useAccountStore} from '../stores/account';
const account=useAccountStore(),items=ref([]),ticker=ref(''),sourceText=ref(''),alias=ref(''),score=ref(null),busy=ref(false),error=ref('');
const percent=value=>value==null?'—':(100*value).toFixed(1)+'%';
const statusLabel=value=>value==='confirmed'?tr('已确认','Confirmed'):value==='rejected'?tr('已拒绝','Rejected'):tr('待审核','Awaiting review');
async function load(){try{items.value=(await productRequest('aliases')).items;}catch{error.value=tr('无法读取名称线索。','Could not read aliases.');}}
async function propose(){busy.value=true;error.value='';try{const result=await productRequest('aliases',{method:'POST',csrfToken:account.session.csrfToken,body:{ticker:ticker.value.toUpperCase(),sourceText:sourceText.value,alias:alias.value||null}});if(result.available===false)error.value=tr('模型未接通，可填写原文中的别名手动提交。','The model is unavailable. Enter an alias from the source text to propose it manually.');else items.value=result.items;}catch{error.value=tr('候选需要包含原文中的别名与依据。','The alias and evidence must appear in the original text.');}finally{busy.value=false;}}
async function review(id,approved){busy.value=true;try{items.value=(await productRequest(`aliases/${id}/confirm`,{method:'POST',csrfToken:account.session.csrfToken,body:{approved}})).items;score.value=null;}catch{error.value=tr('审核保存失败。','Could not save review.');}finally{busy.value=false;}}
async function backtest(){busy.value=true;try{score.value=await productRequest('aliases/backtest',{method:'POST',csrfToken:account.session.csrfToken});}catch{error.value=tr('回测暂时无法运行。','Backtest is unavailable.');}finally{busy.value=false;}}
</script>
<style scoped>
.alias-review{padding:24px 0;border-top:1px solid var(--border);font-size:13px}.alias-review summary{font-family:var(--display-font);font-size:20px;cursor:pointer}.alias-review p,.alias-review small{color:var(--muted);font-size:12px;line-height:1.7}.alias-review form{display:grid;gap:12px;margin:20px 0;max-width:520px}.alias-review label{display:grid;gap:8px}.alias-review input{padding:10px 12px;border:1px solid var(--border);background:transparent;color:var(--text);font:inherit}.alias-review button{padding:9px 14px;border:1px solid var(--border);background:transparent;color:var(--text);font:inherit;cursor:pointer}.alias-review button:disabled{opacity:.6}.alias-review form button{width:max-content}.alias-review article{display:flex;gap:20px;justify-content:space-between;padding:14px 0;border-top:1px solid var(--border)}.alias-review article>div:first-child{display:grid;gap:8px;overflow-wrap:anywhere}.alias-review article>div:last-child{display:flex;align-items:center;gap:8px}
</style>
