<template>
  <section v-if="available || account.session?.operator" class="kol-tracker">
    <div class="kol-heading"><h2>{{ tr('KOL 提及记录','KOL mentions') }}</h2><span>{{ tr('名单账号','Listed accounts') }} {{ listed?.items?.length ?? '—' }}</span></div>
    <p class="kol-note">{{ tr('只统计名单账号提到的站内资产，同一账号与资产只计首次提及。战绩至少需要 10 个有效 24h 样本，数字不表示涨跌由提及引起。','Only site assets mentioned by listed accounts are included, once per account and asset. Rankings need 10 valid 24h samples. Returns do not establish causation.') }}</p>
    <p v-if="!available" class="kol-note">{{ tr('X 读取来源尚未接通，可先维护名单。','X reads are not connected. The account list can be maintained first.') }}</p>
    <form v-if="available" @submit.prevent="lookup"><label>{{ tr('粘贴名单账号的帖子链接','Paste a listed account’s post URL') }}</label><div class="kol-input-row"><input v-model.trim="url" type="url" maxlength="250" required placeholder="https://x.com/…/status/…"><button :disabled="busy || !account.session">{{ busy?tr('读取中…','Reading…'):tr('读取这一条','Read this post') }}</button></div><p v-if="!account.session" class="kol-note"><RouterLink :to="{path:'/me',query:{chain:chainScope(route.query)}}">{{ tr('登录后按需读取','Sign in for on-demand reads') }} →</RouterLink></p></form>
    <form v-if="account.session?.operator" class="kol-list-editor" @submit.prevent="addAccount"><label>{{ tr('添加名单账号','Add a listed account') }}</label><div class="kol-input-row"><input v-model.trim="handle" maxlength="16" placeholder="@username" required><button :disabled="busy">{{ tr('添加','Add') }}</button></div></form>
    <div v-if="listed?.items?.length" class="kol-accounts"><span v-for="item in listed.items" :key="item.handle"><a :href="item.url" target="_blank" rel="noopener noreferrer">@{{ item.handle }} ↗</a><button v-if="account.session?.operator" :aria-label="tr('移出名单','Remove from list')+' '+item.handle" @click="removeAccount(item.handle)">×</button></span></div>
    <p v-if="error" role="alert" class="kol-error">{{ error }}</p>
    <p v-if="pending.length" class="kol-note">{{ tr('同名提及未计入战绩：','Ambiguous mentions excluded from rankings:') }} {{ pending.map(p=>p.symbol).join('、') }}</p>
    <template v-if="records">
      <div v-if="records.ranking.length" class="kol-ranking"><h3>{{ tr('站内战绩','Site performance') }}</h3><article v-for="item in records.ranking" :key="item.handle"><strong>@{{ item.handle }}</strong><span :title="tr('可计算提及后24h涨跌的有效样本数；至少10个才进入战绩','Valid samples with a measurable post-mention 24h return; at least 10 are required for ranking')">{{ tr('样本','Samples') }} {{ item.samples }}</span><span :title="tr('有效样本中提及后24h价格上涨的占比','Share of valid samples with a positive price return 24h after the mention')">{{ tr('24h 胜率','24h positive return') }} {{ (100*item.winRate).toFixed(1) }}%</span><span :title="tr('有效样本提及后24h价格涨跌的中位数（%），不代表因果关系','Median post-mention 24h price return (%) among valid samples; does not establish causation')">{{ tr('24h 中位涨跌','Median return 24h') }} {{ rate(item.medianReturn24h) }}</span></article></div>
      <p v-else class="kol-note">{{ tr('暂无达到样本门槛的账号。','No account meets the sample threshold yet.') }}</p>
      <div class="kol-records"><article v-for="item in records.items" :key="item.postId+item.assetKey"><div><strong>@{{ item.handle }}</strong><RouterLink :to="assetPath(item.assetKey)">{{ item.symbol || short(item.assetKey) }}</RouterLink><small>{{ date(item.postedAt) }} · {{ item.firstMention?tr('首喊','First mention'):tr('后续提及','Later mention') }}</small><a :href="item.url" target="_blank" rel="noopener noreferrer">{{ tr('原帖','Source post') }} ↗</a></div><div><strong :title="tr('提及时的站内美元参考报价；缺失不表示零','Site USD reference quote at the mention; missing does not mean zero')">{{ tr('提及参考价','Mention reference price') }} {{ usd(item.mentionPriceUsd) }}</strong><span :title="tr('相对提及参考价的1h、24h、7d价格涨跌（%）；观测不足时为缺失','1h, 24h and 7d price returns (%) relative to the mention reference quote; missing when observations are insufficient')">{{ tr('提及后涨跌','Post-mention change') }} · 1h {{ rate(item.returns['1h']) }} · 24h {{ rate(item.returns['24h']) }} · 7d {{ rate(item.returns['7d']) }}</span><small :title="tr('已收录价格观测相对提及参考价的最高倍数，不代表完整历史最高价','Maximum recorded price relative to the mention reference quote, not an all-history high')">{{ tr('站内样本最高倍数','Maximum in available samples') }} {{ item.maxMultiple==null?'—':item.maxMultiple.toFixed(2)+'×' }}</small></div></article></div>
      <p v-if="available&&!records.items.length" class="kol-note">{{ tr('尚无记录。读取一条名单账号的帖子后，匹配到的站内资产将出现在这里。','No records yet. Read a listed account’s post to record matched site assets.') }}</p>
    </template>
  </section>
</template>
<script setup>
import { ref,onMounted,watch } from 'vue';
import { useRoute } from 'vue-router';
import { assetNavigationLink } from '../utils/navigation-context';
import { chainScope } from '../utils/chain-scope';
import { useAccountStore } from '../stores/account';
import { productRequest } from '../api/developer';
import { tr } from '../i18n';
import { short,usd,date } from '../utils/format';
const account=useAccountStore(),listed=ref(null),available=ref(false),records=ref(null),pending=ref([]),url=ref(''),handle=ref(''),busy=ref(false),error=ref('');
const route=useRoute();
const rate=value=>value==null?'—':(value>=0?'+':'')+(100*value).toFixed(1)+'%';
const assetPath=key=>{const [chainId,token]=String(key).split(':');return assetNavigationLink({chainId,token},{route,scope:chainScope(route.query)});};
function failure(e){return e.message==='kol-not-allowlisted'?tr('该账号尚未进入名单，需运营确认。','This account is not listed yet. Operator review is required.'):e.message==='invalid-x-post-url'?tr('请输入完整的 X 帖子链接。','Enter a full X post URL.'):e.status===429?tr('读取次数已达当前限制，请稍后再试。','Read limit reached. Please try later.'):tr('暂时无法读取，请重试。','Could not load. Please retry.');}
async function load(){try{listed.value=await productRequest('kol/accounts');available.value=listed.value.available;if(available.value||account.session?.operator)records.value=await productRequest('kol/mentions');}catch(e){error.value=failure(e);}}
async function lookup(){busy.value=true;error.value='';try{const result=await productRequest('kol/lookup',{method:'POST',body:{url:url.value},csrfToken:account.session?.csrfToken});pending.value=result.pending||[];if(result.reason){error.value=tr('来源暂时无法读取，这条帖子未被记录。','The source could not be read. This post was not recorded.');}await load();}catch(e){error.value=failure(e);}finally{busy.value=false;}}
async function addAccount(){busy.value=true;error.value='';try{listed.value=await productRequest('kol/accounts',{method:'POST',body:{handle:handle.value,active:true},csrfToken:account.session.csrfToken});handle.value='';}catch(e){error.value=failure(e);}finally{busy.value=false;}}
async function removeAccount(value){busy.value=true;try{listed.value=await productRequest('kol/accounts',{method:'POST',body:{handle:value,active:false},csrfToken:account.session.csrfToken});}catch(e){error.value=failure(e);}finally{busy.value=false;}}
onMounted(load);
watch(()=>account.session?.user.id,()=>load());
</script>
<style scoped>
.kol-tracker{padding:24px 0;border-block:1px solid var(--border);font-size:13px}.kol-heading{display:flex;justify-content:space-between;align-items:center;gap:16px}.kol-heading h2{font-family:var(--display-font);font-weight:400;font-size:22px;margin:0}.kol-heading>span{font-size:12px;color:var(--muted)}.kol-note{color:var(--muted);font-size:12px;line-height:1.7}.kol-tracker form{margin:18px 0}.kol-input-row{display:flex;gap:8px;margin-top:8px}.kol-input-row input{flex:1;min-width:0;padding:10px 12px;border:1px solid var(--border);background:transparent;color:var(--text);font:inherit}.kol-tracker button{padding:9px 14px;border:1px solid var(--border);background:transparent;color:var(--text);font:inherit;cursor:pointer}.kol-tracker button:disabled{opacity:.5;cursor:wait}.kol-accounts{display:flex;flex-wrap:wrap;gap:10px 20px}.kol-accounts>span{display:flex;gap:6px;align-items:center}.kol-accounts a{color:var(--text);text-decoration:underline;text-underline-offset:4px}.kol-accounts button{padding:3px;border:0}.kol-ranking article{display:flex;flex-wrap:wrap;gap:10px 22px;padding:14px 0;border-top:1px solid var(--border)}.kol-records article{display:flex;justify-content:space-between;gap:20px;padding:18px 0;border-top:1px solid var(--border)}.kol-records article>div{display:grid;gap:8px}.kol-records article>div:last-child{text-align:right}.kol-records small{font-size:12px;color:var(--muted)}.kol-records a{color:var(--text);text-decoration:underline;text-underline-offset:4px}.kol-error{color:var(--loss)}@media(max-width:600px){.kol-input-row{flex-direction:column}.kol-records article{flex-direction:column;gap:14px}.kol-records article>div:last-child{text-align:left}}
</style>
